import Link from "next/link";
import { OpportunityCard } from "@/components/opportunity-card";
import { opportunitySource, quotationSource, sanitizePageParam } from "@/lib/data/source";

type PageProps = { searchParams?: Promise<Record<string, string | string[] | undefined>> };
const PAGE_SIZE = 18;

export default async function Home({ searchParams }: PageProps) {
  const params = await searchParams;
  const currentParams = new URLSearchParams();
  const cleanParams: Record<string, string | string[] | undefined> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    const cleanKey = key.trim(); if (!cleanKey) continue;
    if (Array.isArray(value)) { cleanParams[cleanKey] = value; continue; }
    const cleanValue = value?.trim(); if (cleanValue) { cleanParams[cleanKey] = cleanValue; currentParams.set(cleanKey, cleanValue); }
  }
  const page = sanitizePageParam(cleanParams.page);
  const filters = { city: str(cleanParams.city), category: str(cleanParams.category), expenseGroup: str(cleanParams.expenseGroup), school: str(cleanParams.school), periodStart: str(cleanParams.periodStart), periodEnd: str(cleanParams.periodEnd), query: str(cleanParams.query) };
  const view = str(cleanParams.view) === "history" ? "history" : "open";
  const source = view === "history" ? opportunitySource : quotationSource;
  const result = await source.listOpportunities(filters, { page, pageSize: PAGE_SIZE });
  const exportParams = new URLSearchParams();
  for (const [key, value] of Object.entries(filters)) if (value) exportParams.set(key, value);
  const active = Object.entries(filters).filter(([, value]) => value);
  return <main className="min-h-screen bg-[var(--color-bg-subtle)]">
    <header className="border-b border-[var(--color-border)] bg-[var(--color-bg)]"><div className="shell py-8 sm:py-11">
      <div className="flex flex-wrap items-start justify-between gap-6"><div className="max-w-2xl"><p className="eyebrow text-[var(--color-primary)]">Cotações abertas · Grande BH</p><h1 className="mt-3 text-4xl font-bold leading-none text-[var(--color-fg)] sm:text-5xl">Novas compras<br className="hidden sm:block" /> para enviar proposta.</h1><p className="mt-4 max-w-xl text-base leading-6 text-[var(--color-fg-muted)]">Prazos, escolas e itens do SGD em cards comerciais rápidos.</p></div><div className="grid grid-cols-2 divide-x divide-[var(--color-border)] self-end border-y border-[var(--color-border)] sm:grid-cols-3"><Metric label={view === "history" ? "histórico" : "abertas"} value={result.totalAvailable.toLocaleString("pt-BR")} /><Metric label="encontradas" value={result.total.toLocaleString("pt-BR")} /><Metric className="hidden sm:block" label="municípios" value="7" /></div></div>
    </div></header>
    <section className="border-b border-[var(--color-border)] bg-[var(--color-bg)]"><div className="shell py-5"><div className="mb-4 flex flex-wrap gap-2"><Link className={view === "open" ? "action-primary" : "action-secondary"} href="/">Cotações abertas</Link><Link className={view === "history" ? "action-primary" : "action-secondary"} href="/?view=history">Histórico de compras</Link></div><form className="grid gap-4 lg:grid-cols-[minmax(0,1.7fr)_repeat(3,minmax(0,1fr))_auto]" role="search">{view === "history" && <input name="view" type="hidden" value="history" />}<label className="relative block"><span className="sr-only">Buscar oportunidades</span><input className="field" defaultValue={filters.query} name="query" placeholder="Busque por item, escola ou fornecedor" /></label><Select label="Cidade" name="city" options={result.facets.cities.map(x => [x, x])} value={filters.city} /><Select label="Categoria" name="category" options={result.facets.categories.map(x => [x.slug, x.name])} value={filters.category} /><Select label="Escola" name="school" options={result.facets.schools.map(x => [x, x])} value={filters.school} /><button className="action-primary" type="submit">Buscar</button><details className="lg:col-span-5"><summary className="cursor-pointer text-sm font-semibold text-[var(--color-fg-muted)]">Mais filtros <span className="ml-1 text-[var(--color-primary)]">+</span></summary><div className="mt-4 grid gap-4 sm:grid-cols-3"><Select label="Grupo de despesa" name="expenseGroup" options={result.facets.expenseGroups.map(x => [x, x])} value={filters.expenseGroup} /><label><span className="field-label">{view === "history" ? "Compra a partir de" : "Prazo a partir de"}</span><input className="field mt-1" defaultValue={filters.periodStart} name="periodStart" type="date" /></label><label><span className="field-label">{view === "history" ? "Entrega até" : "Prazo até"}</span><input className="field mt-1" defaultValue={filters.periodEnd} name="periodEnd" type="date" /></label></div></details></form>{active.length > 0 && <div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-[var(--color-fg-muted)]">Filtros ativos</span>{active.map(([key, value]) => <span className="filter-chip" key={key}>{value}</span>)}<Link className="ml-1 text-sm font-semibold text-[var(--color-primary)]" href={view === "history" ? "/?view=history" : "/"}>Limpar tudo</Link></div>}</div></section>
    <section className="shell py-8 sm:py-10"><div className="mb-6 flex flex-wrap items-baseline justify-between gap-3"><h2 className="text-xl font-bold text-[var(--color-fg)]">{result.total.toLocaleString("pt-BR")} {view === "history" ? "compras no histórico" : "cotações abertas"}</h2><div className="flex items-center gap-4"><p className="text-sm text-[var(--color-fg-muted)]">Página {result.page} de {result.totalPages}</p><a className="action-secondary" href={`/api/export?${exportParams.toString()}`}>Exportar</a></div></div>{result.data.length === 0 ? <div className="border-l-4 border-[var(--color-accent)] bg-[var(--color-bg)] p-8"><h2 className="text-lg font-bold">Nenhum resultado com esses filtros</h2><p className="mt-2 text-sm text-[var(--color-fg-muted)]">Remova algum filtro ou amplie o período.</p></div> : <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{result.data.map(o => <OpportunityCard key={o.externalId} opportunity={o} />)}</div>}<Pagination currentParams={currentParams} page={result.page} totalPages={result.totalPages} /></section>
  </main>;
}
const str = (value: string | string[] | undefined) => typeof value === "string" ? value : undefined;
function Metric({ label, value, className = "" }: { label: string; value: string; className?: string }) { return <div className={`px-4 py-2 ${className}`}><p className="text-2xl font-bold tabular-nums text-[var(--color-fg)]">{value}</p><p className="eyebrow mt-1">{label}</p></div>; }
function Select({ label, name, options, value }: { label: string; name: string; options: string[][]; value?: string }) { return <label><span className="field-label">{label}</span><select className="field mt-1" defaultValue={value ?? ""} name={name}><option value="">Todas</option>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function Pagination({ currentParams, page, totalPages }: { currentParams: URLSearchParams; page: number; totalPages: number }) { if (totalPages <= 1) return null; const prev = new URLSearchParams(currentParams); prev.set("page", `${Math.max(1,page-1)}`); const next = new URLSearchParams(currentParams); next.set("page", `${Math.min(totalPages,page+1)}`); return <nav className="mt-10 flex items-center justify-between border-t border-[var(--color-border)] pt-5"><a aria-disabled={page <= 1} className="action-secondary" href={`/?${prev}`}>← Anterior</a><p className="text-sm font-medium text-[var(--color-fg-muted)]">{page} / {totalPages}</p><a aria-disabled={page >= totalPages} className="action-secondary" href={`/?${next}`}>Próxima →</a></nav>; }
